### ISSUE TITLE
Gem not in rubygems.org

### ISSUE THREAD

**Issue by zavan** [thoughtbot/clearance-i18n#4]
> Fetching gem metadata from https://rubygems.org/............
> Fetching version metadata from https://rubygems.org/...
> Fetching dependency metadata from https://rubygems.org/..
> Could not find gem 'clearance-i18n (>= 0) ruby' in any of the gem sources listed in your Gemfile or installed on this
machine.

This gem is not listed in [rubygems.org](https://rubygems.org/search?utf8=%E2%9C%93&query=clearance-i18n), is this intentional?

Thanks

**Comment by JulienItard** [comment]
:+1:
